### PR TITLE
renamed Type classes for php7 support

### PR DESCRIPTION
**Pull request by younes0**
see #71

### CODE REVIEW

**Comment by RuslanZavacky** [comment]
@younes0 I suggest to add PHP 5.7 to the Travis test version. And tests require fixing too :)

**Comment by younes0** [comment]
@RuslanZavacky you're right, will do it soon

**Comment by younes0** [comment]
errors in test, can't do better...

**Comment by Flyingmana** [comment]
Dont know about the Twig changes, but the php7 related changes look good for me

**Comment by younes0** [comment]
I'd love to have feedbacks from @raulfraile :)

**Comment by raulfraile** [comment]
Thank you!

**Pull request merged**
